# startup_session ~/.config/kitty/startup.conf
background            #000000
foreground            #ffffff
cursor                #bbbbbb
selection_background  #00a48c
color0                #000000
color8                #545454
color1                #9f0000
color9                #ff0000
color2                #008b00
color10               #00ee00
color3                #41a4ad
color11               #ffff00
color4                #0081ff
color12               #0000ff
color5                #bc00ca
color13               #ff00ff
color6                #31949d
color14               #01646d
color7                #bbbbbb
color15               #00ffff
selection_foreground #000000
font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
shell zsh
background_opacity 0.75


# Включаем режим выделения клавиатурой по нажатию Shift + стрелки
keyboard_select yes
map shift+left  keyboard_select_left
map shift+right keyboard_select_right
map shift+up    keyboard_select_up
map shift+down  keyboard_select_down

# Копирование выделенного
map ctrl+shift+c copy_to_clipboard

# Выход из режима выделения
map escape keyboard_select_reset
# fastfetch
